name: Build

on:
  push:
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            cmake \
            libwxgtk3.2-dev 
            libboost-all-dev

      - name: Configure
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cmake --build build -j
